/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sabrina' at '11.01.16 12:34' with Gradle 2.6
 *
 * @author Sabrina, @date 11.01.16 12:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
